### ISSUE TITLE
[Question] Adoption path in FreeBSD

### ISSUE THREAD

**Issue by ngortheone** [YutaroHayakawa/generic-ebpf#5]
Hi @YutaroHayakawa I enjoyed your talk on 2018, but unfortunately there has been little news since. It looks like you are still working on eBPF for FreeBSD so I am curious if there is any real perspective for this project to be adopted into FreeBSD source tree?

Also where would you recommend to go to get the latest updates on this project? (Blog/Twitter etc?)
Thanks

**Comment by YutaroHayakawa** [comment]
Unfortunately, I currently not able to work with this project actively and it is pending right now. So, no concrete plan for landing on FreeBSD :(

**Comment by YutaroHayakawa** [comment]
Seems this question is outdated. Let me close this. Feel free to reopen when you have further question.
