### ISSUE TITLE
README.md was not updated when jit compiler was removed

### ISSUE THREAD

**Issue by Alan-Jowett** [YutaroHayakawa/generic-ebpf#7]
https://github.com/generic-ebpf/generic-ebpf#notes talks about using ubpf as the jit compiler for generic-ebpf, but it looks like that was removed via this commit: https://github.com/generic-ebpf/generic-ebpf/commit/bb4a3d02c5b3252da5beca95d023b5906616621c

Shouldn't the README.md be updated as well?

**Comment by YutaroHayakawa** [comment]
Yes, thanks for pointing it out! Removed in https://github.com/generic-ebpf/generic-ebpf/commit/c9cee73c73845c9d60aef807b7ee7891987cd6fd .
